"""empty message

Revision ID: f3380c7d4b63
Revises: f100a4076a7f
Create Date: 2019-11-10 20:36:53.426970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3380c7d4b63'
down_revision = 'f100a4076a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_photo'), 'users', ['photo'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_photo'), table_name='users')
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###
